version: '3.9'

services:
  dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -inMemory -cors *"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal


  auth:
    build: .
    depends_on:
     - "dynamodb-local"
    links:
     - "dynamodb-local"
    container_name: auth
    restart: always
    entrypoint: sleep infinity
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app

  rabbitmq-cluster:
      image: pedronx/rabbitmq
      container_name: rabbitmq-cluster
      ports: 
        - 25672:25672
        - 15672:15672
        - 5672:5672
      restart: always