apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 2
  template:
    metadata:
      labels:
        app: "auth"
    spec:
      containers:
        - name: auth
          image: "pedronx/auth"
          resources:
            requests:
              memory: 1000Mi
              cpu: "2"
            limits:
              memory: 1000Mi
              cpu: "2"
          startupProbe:
            httpGet:
              path: /healthz
              port: 3333
            failureThreshold: 1
            periodSeconds: 3
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3333
            failureThreshold: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3333
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            periodSeconds: 5